package icelake

import (
	"context"
	"fmt"
	"net/url"
	"path"
	"path/filepath"
	"strings"

	"github.com/gvkhna/icelake/internal/catalogdb"
)

// DuckDBInitTable identifies one schema-declared table.
type DuckDBInitTable struct {
	Namespace string
	Name      string
}

// DuckDBInitOptions is the resolved writer configuration needed to generate a
// DuckDB setup script. It does not execute DuckDB or query data.
type DuckDBInitOptions struct {
	CacheDir    string
	CatalogPath string
	LocalOnly   bool
	Endpoint    string
	Bucket      string
	Prefix      string
	Region      string
	Tables      []DuckDBInitTable
}

// DuckDBInit returns SQL which installs DuckDB's required extensions, configures
// its durable HTTP cache, and creates one schema-qualified view per table.
func DuckDBInit(ctx context.Context, opts DuckDBInitOptions) (string, error) {
	if opts.CacheDir == "" {
		return "", fmt.Errorf("cache directory is empty")
	}
	if len(opts.Tables) == 0 {
		return "", fmt.Errorf("no tables selected")
	}

	var b strings.Builder
	b.WriteString("-- Generated by icelake duckdb-init. Run this file with DuckDB's -init option.\n")
	b.WriteString("INSTALL httpfs;\nINSTALL iceberg;\nINSTALL cache_httpfs FROM community;\n")
	b.WriteString("LOAD httpfs;\nLOAD iceberg;\nLOAD cache_httpfs;\n")
	b.WriteString("SET TimeZone='UTC';\n")
	fmt.Fprintf(&b, "SET cache_httpfs_cache_directory=%s;\n", literal(filepath.Join(opts.CacheDir, "duckdb-cache")))
	b.WriteString("SET cache_httpfs_enable_cache_validation=true;\n\n")

	if !opts.LocalOnly {
		endpoint, err := parseEndpoint(opts.Endpoint)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "-- DuckDB must inherit ICELAKE_ACCESS_KEY_ID and ICELAKE_SECRET_ACCESS_KEY.\n")
		fmt.Fprintf(&b, "SET s3_endpoint=%s;\n", literal(endpoint.Host))
		fmt.Fprintf(&b, "SET s3_use_ssl=%t;\n", endpoint.Scheme == "https")
		b.WriteString("SET s3_url_style='path';\n")
		fmt.Fprintf(&b, "SET s3_region=%s;\n", literal(opts.Region))
		b.WriteString("SET s3_access_key_id=getenv('ICELAKE_ACCESS_KEY_ID');\n")
		b.WriteString("SET s3_secret_access_key=getenv('ICELAKE_SECRET_ACCESS_KEY');\n\n")
	}

	type view struct {
		table  DuckDBInitTable
		source string
	}
	views := make([]view, 0, len(opts.Tables))
	for _, table := range opts.Tables {
		var source string
		if opts.LocalOnly {
			glob := filepath.Join(opts.CacheDir, table.Namespace, table.Name, "data", "*.parquet")
			matches, err := filepath.Glob(glob)
			if err != nil {
				return "", fmt.Errorf("checking local cache for %s.%s: %w", table.Namespace, table.Name, err)
			}
			if len(matches) == 0 {
				return "", fmt.Errorf("local cache has no committed Parquet files for %s.%s", table.Namespace, table.Name)
			}
			source = fmt.Sprintf("read_parquet(%s, union_by_name = true)", literal(glob))
		} else {
			metadata, err := catalogdb.MetadataLocation(ctx, opts.CatalogPath, table.Namespace, table.Name)
			if err != nil {
				return "", fmt.Errorf("resolving current metadata for %s.%s: %w; run icelake rebuild", table.Namespace, table.Name, err)
			}
			if err := validateMetadataLocation(metadata, opts.Bucket, opts.Prefix, table); err != nil {
				return "", err
			}
			source = fmt.Sprintf("iceberg_scan(%s)", literal(metadata))
		}
		views = append(views, view{table: table, source: source})
	}
	for _, view := range views {
		fmt.Fprintf(&b, "CREATE SCHEMA IF NOT EXISTS %s;\n", identifier(view.table.Namespace))
		fmt.Fprintf(&b, "CREATE OR REPLACE VIEW %s.%s AS SELECT * FROM %s;\n\n", identifier(view.table.Namespace), identifier(view.table.Name), view.source)
	}
	return b.String(), nil
}

func parseEndpoint(raw string) (*url.URL, error) {
	endpoint, err := url.Parse(raw)
	if err != nil || endpoint.Host == "" || (endpoint.Scheme != "http" && endpoint.Scheme != "https") ||
		endpoint.User != nil || endpoint.RawQuery != "" || endpoint.Fragment != "" || (endpoint.Path != "" && endpoint.Path != "/") {
		return nil, fmt.Errorf("invalid S3 endpoint %q: require an http(s) origin with no path, query, fragment, or userinfo", raw)
	}
	return endpoint, nil
}

func validateMetadataLocation(metadata, bucket, prefix string, table DuckDBInitTable) error {
	location, err := url.Parse(metadata)
	if err != nil || location.Scheme != "s3" || location.Host != bucket || location.RawQuery != "" || location.Fragment != "" {
		return fmt.Errorf("catalog metadata location for %s.%s is not an S3 location in the configured bucket", table.Namespace, table.Name)
	}
	want := path.Join("/", prefix, table.Namespace, table.Name, "metadata") + "/"
	if !strings.HasPrefix(location.Path, want) || !strings.HasSuffix(location.Path, ".metadata.json") {
		return fmt.Errorf("catalog metadata location for %s.%s is outside its configured warehouse path", table.Namespace, table.Name)
	}
	return nil
}

func literal(s string) string    { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }
func identifier(s string) string { return `"` + strings.ReplaceAll(s, `"`, `""`) + `"` }
