package main

import (
	"bytes"
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gvkhna/icelake/internal/testsubstrate"
)

func TestDuckDBInitEmitsCacheSetupAndQualifiedViews(t *testing.T) {
	dir := localOnlyEnv(t)
	cacheData := filepath.Join(dir, "cache", "market", "fills", "data")
	if err := os.MkdirAll(cacheData, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(cacheData, "part.parquet"), nil, 0o644); err != nil {
		t.Fatal(err)
	}
	var stdout bytes.Buffer
	if err := runDuckDBInit(context.Background(), nil, &stdout); err != nil {
		t.Fatalf("runDuckDBInit: %v", err)
	}
	if !strings.Contains(stdout.String(), "INSTALL cache_httpfs FROM community;") {
		t.Fatal("duckdb-init did not require cache_httpfs")
	}
	if !strings.Contains(stdout.String(), `CREATE OR REPLACE VIEW "market"."fills"`) {
		t.Fatal("duckdb-init did not create a qualified view")
	}
}

// TestDuckDBInitScriptQueriesTheRealLocalCache is scenario 13's local-only
// command boundary extended to the generated DuckDB product: records travel
// through the installed command, and a real independent DuckDB executes the
// exact emitted setup before reading the qualified view. Local-only has no
// object-store substrate by definition.
func TestDuckDBInitScriptQueriesTheRealLocalCache(t *testing.T) {
	dir := localOnlyEnv(t)
	const records = 3
	var input strings.Builder
	for i := range records {
		input.WriteString(fillLine(i) + "\n")
	}
	if code, out := pipeInto(t, append(os.Environ(), localOnlyEnvPairs(t, dir)...), input.String()); code != exitOK {
		t.Fatalf("icelake run exit code = %d, want %d\n%s", code, exitOK, out)
	}

	var script bytes.Buffer
	if err := runDuckDBInit(context.Background(), []string{"market.fills"}, &script); err != nil {
		t.Fatalf("runDuckDBInit: %v", err)
	}
	duck := openDuckDB(t)
	for _, statement := range strings.Split(script.String(), ";") {
		statement = strings.TrimSpace(statement)
		statement = strings.TrimSpace(strings.TrimPrefix(statement, "-- Generated by icelake duckdb-init. Run this file with DuckDB's -init option."))
		if statement == "" {
			continue
		}
		if _, err := duck.ExecContext(context.Background(), statement); err != nil {
			if strings.HasPrefix(statement, "INSTALL ") {
				t.Skipf("cannot install DuckDB extension required by duckdb-init (%q): %v", statement, err)
			}
			t.Fatalf("duckdb %q: %v", statement, err)
		}
	}
	var total int
	queryRow(t, duck, `SELECT count(*) FROM "market"."fills"`, &total)
	if total != records {
		t.Errorf("generated view returned %d rows, want %d", total, records)
	}
	var price string
	queryRow(t, duck, `SELECT CAST(price AS VARCHAR) FROM "market"."fills" WHERE symbol = 'SYM0'`, &price)
	if price != "0.500000000" {
		t.Errorf("generated view price = %q, want %q", price, "0.500000000")
	}
}

// TestDuckDBInitBucketScriptQueriesTheRealIcebergTable proves the command's
// defining promise at the real boundary: callers run the same qualified query
// against a generated script whether icelake kept the table local or committed
// it to an object store.
func TestDuckDBInitBucketScriptQueriesTheRealIcebergTable(t *testing.T) {
	testsubstrate.RequireDocker(t)
	bucket := testsubstrate.StartMinIO(t)
	dir := t.TempDir()
	env := bucketEnv(t, bucket, dir, twoTableDocument)
	if code, out := pipeInto(t, env, fillLine(0)+"\n"+fillLine(1)+"\n"); code != exitOK {
		t.Fatalf("icelake run exit code = %d, want %d\n%s", code, exitOK, out)
	}
	t.Setenv(envDataDir.name, dir)
	t.Setenv(envSchemaFile.name, writeDocument(t, dir, twoTableDocument))
	t.Setenv(envEndpoint.name, bucket.Endpoint)
	t.Setenv(envBucket.name, bucket.Bucket)
	t.Setenv(envPrefix.name, "warehouse")
	t.Setenv(envRegion.name, bucket.Region)
	t.Setenv(envAccessKeyID.name, "recognizable-access-key")
	t.Setenv(envSecretAccessKey.name, "recognizable-secret-key")
	t.Setenv(envLocalOnly.name, "false")

	var script bytes.Buffer
	if err := runDuckDBInit(context.Background(), []string{"market.fills"}, &script); err != nil {
		t.Fatalf("runDuckDBInit: %v", err)
	}
	if strings.Contains(script.String(), "recognizable-access-key") || strings.Contains(script.String(), "recognizable-secret-key") {
		t.Fatal("generated script contains a credential value")
	}
	if strings.Contains(script.String(), "unsafe_enable_version_guessing") {
		t.Fatal("generated script enables unsafe metadata guessing")
	}

	// getenv is deliberately a DuckDB CLI-only function. The command's product is
	// an init script for that CLI, while this suite uses DuckDB's Go embedding;
	// substitute the two references solely to exercise the generated bucket
	// view through the same engine without ever putting a credential in product
	// output.
	executableScript := strings.ReplaceAll(script.String(), "getenv('ICELAKE_ACCESS_KEY_ID')", "'"+bucket.AccessKeyID+"'")
	executableScript = strings.ReplaceAll(executableScript, "getenv('ICELAKE_SECRET_ACCESS_KEY')", "'"+bucket.SecretAccessKey+"'")
	duck := openDuckDB(t)
	for _, statement := range strings.Split(executableScript, ";") {
		statement = strings.TrimSpace(statement)
		statement = strings.TrimSpace(strings.TrimPrefix(statement, "-- Generated by icelake duckdb-init. Run this file with DuckDB's -init option."))
		if statement == "" {
			continue
		}
		if _, err := duck.ExecContext(context.Background(), statement); err != nil {
			if strings.HasPrefix(statement, "INSTALL ") {
				t.Skipf("cannot install DuckDB extension required by duckdb-init (%q): %v", statement, err)
			}
			t.Fatalf("duckdb %q: %v", statement, err)
		}
	}
	var total int
	queryRow(t, duck, `SELECT count(*) FROM "market"."fills"`, &total)
	if total != 2 {
		t.Errorf("generated bucket view returned %d rows, want 2", total)
	}
}

func TestDuckDBInitRefusesUnknownSelection(t *testing.T) {
	localOnlyEnv(t)
	var stdout bytes.Buffer
	err := runDuckDBInit(context.Background(), []string{"market.unknown"}, &stdout)
	if !errors.Is(err, errUsage) {
		t.Fatalf("runDuckDBInit error = %v, want usage refusal", err)
	}
}
