// Package staging is the local write-ahead durability layer.
//
// Every record is committed to a SQLite staging database before Insert returns,
// independent of the in-memory batch it will eventually belong to, so a process
// crash between accepting a record and committing its batch cannot lose it.
// This package owns the embedded goose migrations, the generated query code,
// the replay index, and the counters backing the staging ceiling.
//
// Since M11 it also owns the local Parquet spool's durable state: which files
// are in the cache directory, what shape each was written under, and which of
// them have reached a bucket. The files themselves are internal/spool's; the
// rows describing them are here, in the same database as the staging rows they
// are written and pruned in step with.
//
// This is the one file in icelake that is not reconstructable. The catalog is
// explicitly rebuildable from the bucket; the staging database is by definition
// holding data not yet copied there, so whoever operates icelake needs their own
// backup story for it — plus any spool file whose row still has a null
// committed_at, which is the other thing that has not reached the bucket. A
// committed spool file is as disposable as the catalog: it is byte-identical to
// an object already in a committed snapshot.
//
// # The database
//
// One staging.db per process, shared by every table — not one file per table.
// SQLite allows one writer at a time, so two tables' inserts serialize; that
// costs nothing for this workload, where an insert is a single-row append and
// the slow thing is an upload that holds no SQLite lock. What it buys is one
// file to back up, one migration run at startup, and a replay pass that reads
// every table's pending rows at once rather than one file's worth at a time.
//
// [Open] sets and then asserts three pragmas: journal_mode=WAL, so the replay
// and flush paths read while the insert path writes; synchronous=FULL rather
// than WAL's usual NORMAL, which is the one place this design pays for
// durability instead of speed; and a busy timeout, so brief lock contention
// between two tables' inserts becomes a short wait inside the driver instead of
// an SQLITE_BUSY error reaching a caller. The driver is modernc.org/sqlite,
// which is pure Go: icelake's own runtime needs no cgo.
//
// # Schema and migrations
//
//	staging(id, namespace, table_name, batch_key, schema_fp, payload,
//	        byte_len, created_at, quarantined_at, quarantine_error)
//	staging_schemas(fp, descriptor)
//	spool_files(batch_key, namespace, table_name, schema_fp, byte_len,
//	            created_at, committed_at)
//	spool_schemas(fp, descriptor)
//
// spool_schemas is deliberately not a reuse of staging_schemas. staging_schemas
// is pruned once no staged row names a fingerprint, which is right there because
// a descriptor exists to decode staged payloads; a spool file outlives its staged
// rows by design, so sharing one table would prune a file's shape out from under
// it seconds after recording it — and that shape is what the transition drain
// reads, possibly years later, to create the table and reconcile it forward.
//
// There is no index beyond each table's primary key, deliberately. The entire
// access pattern is: insert a row, scan the whole (ceiling-bounded) table once
// in id order without reading payloads, and then read, update and delete rows by
// id. The primary key covers all of it, and an index costs writes and disk for a
// lookup nothing performs. AUTOINCREMENT rather than a plain INTEGER PRIMARY KEY
// is load-bearing: rows are continuously deleted as batches commit, and replay
// order must stay insert order, which requires ids never to be reused.
//
// Migrations live in migrations/, are embedded with //go:embed so goose needs no
// files on disk at run time, and are applied by [Open] on every start. goose is
// used strictly as a library; there is no goose CLI anywhere in this project's
// workflow, and no manual migration step for an operator to remember. A failed
// migration fails the open — icelake never serves writes against a database
// whose schema state it is unsure of — and, because goose rolls a failed
// migration back and does not record it, leaves the database exactly as the
// previous binary left it.
//
// The query code is generated by sqlc from migrations/ plus queries.sql and is
// committed, so a plain `go build` never needs the generator. Because sqlc reads
// the same migrations goose applies, the generated code and the shipped schema
// cannot drift apart: there is one description of this schema in the repo.
//
// # What the layers above do with it
//
// [Store.Scan] is called twice over, by two callers with different jobs.
// Process startup calls it once, before any writer exists, and uses two things
// from the result: the totals that seed the ceiling counters, and the refusal
// this package raises for a staging database left in a state this build will
// not replay. It keeps no index. Opening a writer calls it again, per open, and
// that caller claims one table's group with [Index.Claim] and reads exactly
// those rows' payloads back by primary key through [Store.Rows]. Either way a
// scan is one unfiltered ordered pass followed by primary-key lookups — which
// is why no index on (namespace, table_name) exists or is needed.
//
// Rescanning per open rather than handing out slices of one startup snapshot is
// the M4 decision recorded in ARCHITECTURE.md under "Local write-ahead
// durability", and the short form of it is that a snapshot taken at process
// start cannot contain rows staged during a writer's own life. See [Index],
// where the fifth-round correction of this paragraph and of the seven other
// places in this package that carried the superseded wording is written out.
//
// Accepting a record is [Store.Append], which records the payload and the
// descriptor it was encoded under in one transaction, so no staged row can exist
// whose shape is unrecorded. Sealing a batch is [Store.Seal], which stamps the
// batch key on exactly its rows — durably, before the batch is encoded, which is
// what makes crash recovery reproduce the same batch and therefore the same
// content-hash object key. After a commit is confirmed, [Store.Delete] prunes
// the rows and [Store.PruneSchemas] drops descriptors nothing references any
// more. A batch that cannot be encoded is marked with [Store.Quarantine] instead
// of being retried forever.
//
// The spool's own calls follow the same shape, and there are nine of them.
// [Store.RecordSpoolFile] records a file and the descriptor it was written under
// in one transaction, after the bytes are already on disk, and re-records both
// when the same batch is written again — the shape and the size can move under
// one key, because a sealed batch keeps its stored key across a replay that
// re-encodes it. [Store.MarkSpoolCommitted] records that a file has reached a
// bucket, which is the moment it becomes evictable. [Store.SpoolBacklog],
// [Store.SpoolBacklogTables] and [Store.SpoolSchema] are what the transition
// drain walks: which files a table still owes a bucket, which tables owe one at
// all, and the shape each of those files was written under. [Store.SpoolEvictable],
// [Store.SpoolCommittedBytes], [Store.DeleteSpoolFile] and
// [Store.PruneSpoolSchemas] are what retention walks: what may be deleted, how
// much of it there is, forgetting one, and dropping the descriptors nothing
// names any more. The protection for a file that has never been uploaded is the
// shape of those last four statements rather than a rule in the sweeper: such a
// file is not visible to them at all.
//
// Nothing in this package decides *when* any of that happens: there is no
// batching, no timer, no upload and no retry here. It stores what it is told to
// store, atomically, and reports what it holds.
package staging
