// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package staging

import (
	"database/sql"
)

type SpoolFile struct {
	BatchKey    string
	Namespace   string
	TableName   string
	SchemaFp    string
	ByteLen     int64
	CreatedAt   int64
	CommittedAt sql.NullInt64
}

type SpoolSchema struct {
	Fp         string
	Descriptor []byte
}

type Staging struct {
	ID              int64
	Namespace       string
	TableName       string
	BatchKey        sql.NullString
	SchemaFp        string
	Payload         []byte
	ByteLen         int64
	CreatedAt       int64
	QuarantinedAt   sql.NullInt64
	QuarantineError sql.NullString
}

type StagingSchema struct {
	Fp         string
	Descriptor []byte
}
